[package]
name = "gr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.61"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.1", features = ["derive"] }
clap_complete = "4.1.0"
color-eyre = "0.6.2"
colored = "2.0.0"
dirs = "4.0.0"
futures = "0.3.25"
git2 = { version = "0.16.0", features = ["vendored-libgit2"] }
open = "3.2.0"
reqwest = { version = "0.11.13", features = ["json", "native-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1.2"
