[package]
name = "gr-bin"
description = "Interact with remote repositories like you interact with git"
version = "0.1.0-rc15"
edition = "2021"
license = "MIT"
documentation = "https://github.com/daniel7grant/gr"
repository = "https://github.com/daniel7grant/gr"

[dependencies]
async-trait = "0.1.61"
atty = "0.2.14"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.1", features = ["derive"] }
clap_complete = "4.1.0"
color-eyre = "0.6.2"
colored = "2.0.0"
dirs = "4.0.0"
futures = "0.3.25"
git2 = { version = "0.16.0", features = ["vendored-libgit2", "vendored-openssl"] }
inquire = "0.5.3"
open = "3.2.0"
reqwest = { version = "0.11.13", features = ["json", "rustls-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "time"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
urlencoding = "2.1.2"

[[bin]]
name = "gr"
path = "src/main.rs"

[profile.release]
strip = true