name: Release on npm

on: push

jobs:
  release:
    name: Release on npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v3
      - name: Setup latest stable Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./npm/package.json
