name: Release

on:
  release:
    types: [created]

jobs:
  package:
    name: Package up for ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            target: x86_64-pc-windows-gnu
            archive: zip
          - name: Linux
            target: x86_64-unknown-linux-musl
            archive: tar.gz
          - name: MacOS
            target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@v3
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
