name: Test

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v3
      - name: Add toolchain for Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test if release builds correctly
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Release on tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
