name: Test

on: push

permissions:
  contents: write

jobs:
  test:
    name: Test building and release on tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the tag
        uses: actions/checkout@v3
      - name: Add toolchain for Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test if release builds correctly
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
      # Release procedure
      - name: Build for Windows
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
          use-cross: true
      - name: Build for MacOS
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --release --target x86_64-apple-darwin
          use-cross: true
      - name: Release on tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/gr
            target/x86_64-apple-darwin/release/gr
            target/x86_64-pc-windows-gnu/release/gr.exe